// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJL-XZfzA4o1PaC3HM6ZYeRtAGZ32RqPI',
    appId: '1:530515545021:web:c4e2bae3f6b9fafb9d20d4',
    messagingSenderId: '530515545021',
    projectId: 'mobilebancodedados',
    authDomain: 'mobilebancodedados.firebaseapp.com',
    storageBucket: 'mobilebancodedados.appspot.com',
    measurementId: 'G-HQQC93ZQJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb3xiYEByoq8laYKc-AVs_fLI0Vv_cs74',
    appId: '1:530515545021:android:08e667d5b0084d7c9d20d4',
    messagingSenderId: '530515545021',
    projectId: 'mobilebancodedados',
    storageBucket: 'mobilebancodedados.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyTSUO0sgfXNBwsrEUaS992WZlbO6Hl3U',
    appId: '1:530515545021:ios:7e805ede12203dea9d20d4',
    messagingSenderId: '530515545021',
    projectId: 'mobilebancodedados',
    storageBucket: 'mobilebancodedados.appspot.com',
    iosBundleId: 'com.example.teste2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyTSUO0sgfXNBwsrEUaS992WZlbO6Hl3U',
    appId: '1:530515545021:ios:9b1cc3181c0129679d20d4',
    messagingSenderId: '530515545021',
    projectId: 'mobilebancodedados',
    storageBucket: 'mobilebancodedados.appspot.com',
    iosBundleId: 'com.example.teste2.RunnerTests',
  );
}
